FROM adoptopenjdk/openjdk11

ARG JAR_FILE=exec/*.jar
ENV APP_THROTTLE_RATELIMIT_TIME-DURATION=3600
ENV APP_THROTTLE_RATELIMIT_VOLUME=100
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]